
# 어플리케이션 시작 후 동작 가능합니다.
# ./gradlew bootRun
# 더 여러 케이스의 경우 test 폴더에 있는 테스트 코드를 참고해주세요.

### 일반 사용자는 로그인 할 수 있다.
POST http://localhost:8080/v1/auth/users/login
Content-Type: application/json

{
  "email": "user@test.com",
  "password": "qwe123"
}

### 이메일이 존재하지 않는 경우 로그인에 실패한다.
POST http://localhost:8080/v1/auth/users/login
Content-Type: application/json

{
  "email": "this_Is_Not_User@test.com",
  "password": "qwe123"
}

### 마켓은 로그인 할 수 있다.
POST http://localhost:8080/v1/auth/market/login
Content-Type: application/json

{
  "email": "market@market.com",
  "password": "qwe123"
}

### 이메일이 존재하지 않는 경우 로그인에 실패한다.
POST http://localhost:8080/v1/auth/market/login
Content-Type: application/json

{
  "email": "this_Is_Not_Market@test.com",
  "password": "qwe123"
}
